.TH "Tests.cpp" 3 "Quarta, 28 de Setembro de 2016" "Trabalho 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/gtest\&.h'\fP
.br
\fC#include 'trab2\&.h'\fP
.br

.SS "Funções"

.in +1c
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, I)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, V)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, X)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, L)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, C)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, D)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, M)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, MixIVXL)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, MixIVXC)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, MixIVXLC)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, MixIVXLCD)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, MixIVXLCDM)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, MMDCCCLV)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTestTest, end)"
.br
.ti -1c
.RI "\fBTEST\fP (processa_romanosTest, invalidos)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Funções"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definição na linha 85 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, I)"

.PP
Definição na linha 8 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, V)"

.PP
Definição na linha 12 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, X)"

.PP
Definição na linha 17 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, L)"

.PP
Definição na linha 22 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, C)"

.PP
Definição na linha 27 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, D)"

.PP
Definição na linha 32 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, M)"

.PP
Definição na linha 37 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, MixIVXL)"

.PP
Definição na linha 42 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, MixIVXC)"

.PP
Definição na linha 47 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, MixIVXLC)"

.PP
Definição na linha 52 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, MixIVXLCD)"

.PP
Definição na linha 57 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, MixIVXLCDM)"

.PP
Definição na linha 62 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, MMDCCCLV)"

.PP
Definição na linha 67 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTestTest, end)"

.PP
Definição na linha 72 do arquivo Tests\&.cpp\&.
.SS "TEST (processa_romanosTest, invalidos)"

.PP
Definição na linha 75 do arquivo Tests\&.cpp\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Trabalho 2 a partir de seu código-fonte\&.
